version: "3.9"  # optional since v1.27.0
services:
  websocket_server:
    build: ./websocket_server
    image: node
    ports:
      # The following binds container's TCP port 3000 to the host's port 3000
      - "3000:3000"
  client_device:
    build: ./client_device
    image: node
    ports:
      - "3001:3001"
volumes:
  logvolume01: {}